name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Setup .env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }} >> .env
          echo R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }} >> .env
          echo R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }} >> .env
          echo R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }} >> .env
          echo R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }} >> .env

      - name: Start
        run: pm2 restart conforferias_back
